Fix runtime error
Previously, when run in streaming mode, the job would fail with:

```
org.apache.spark.sql.AnalysisException: Append output mode not
supported when there are streaming aggregations on streaming
DataFrames/DataSets without watermark
```

This makes the watermark part of the aggregation.

Conflicts:
	src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala